name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  path:
    description: 'site directory (11ty will compile what is whithin directory)'
    default: './'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
